# Generated by Django 3.2.8 on 2022-06-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
