# Generated by Django 3.2.8 on 2022-05-31 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_research', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='research',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_research', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='protect',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_protect', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='protect',
            name='protection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protections', related_query_name='protections', to='research.research'),
        ),
        migrations.AddField(
            model_name='protect',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_protect', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='production',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='production',
            name='production',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', related_query_name='products', to='research.research'),
        ),
        migrations.AddField(
            model_name='production',
            name='type_product',
            field=models.ManyToManyField(blank=True, related_name='_research_production_type_product_+', to='research.ProductTypes'),
        ),
        migrations.AddField(
            model_name='production',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_production', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_photo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='photos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', related_query_name='photos', to='research.research'),
        ),
        migrations.AddField(
            model_name='photo',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_photo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phenology',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_phenology', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phenology',
            name='month_eggs',
            field=models.ManyToManyField(blank=True, to='research.Months', verbose_name='Month of eggs+'),
        ),
        migrations.AddField(
            model_name='phenology',
            name='month_fungus',
            field=models.ManyToManyField(blank=True, related_name='_research_phenology_month_fungus_+', to='research.Months'),
        ),
        migrations.AddField(
            model_name='phenology',
            name='month_larva',
            field=models.ManyToManyField(blank=True, related_name='_research_phenology_month_larva_+', to='research.Months'),
        ),
        migrations.AddField(
            model_name='phenology',
            name='month_m',
            field=models.ManyToManyField(blank=True, related_name='_research_phenology_month_m_+', to='research.Months'),
        ),
        migrations.AddField(
            model_name='phenology',
            name='month_mature',
            field=models.ManyToManyField(blank=True, related_name='_research_phenology_month_mature_+', to='research.Months'),
        ),
        migrations.AddField(
            model_name='phenology',
            name='phenology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phenology', related_query_name='phenology', to='research.research'),
        ),
        migrations.AddField(
            model_name='phenology',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_phenology', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', related_query_name='notes', to='research.research'),
        ),
        migrations.AddField(
            model_name='note',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experiment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_experiment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experiment',
            name='experiments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiments', related_query_name='experiments', to='research.research'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_experiment', to=settings.AUTH_USER_MODEL),
        ),
    ]
