# Generated by Django 3.2.8 on 2022-05-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phenology',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='production',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='protect',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='research',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
