# Generated by Django 3.2.8 on 2022-06-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20220531_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('type', models.CharField(default='', max_length=300)),
                ('add_data', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
